#!/bin/sh

FIFO="/tmp/dvtm-status.$$"

[ -p "$FIFO" ] || mkfifo -m 600 "$FIFO" || exit 1

while true; do
    # Show the load average, current date (Sun Jan 01 2010), and current time (01:01:01)
	echo "[`cat /proc/loadavg | cut -f1,2,3 -d' '`][ `date +'%a %b %d %Y %T'` ]"
	sleep 1
done > "$FIFO" &

STATUS_PID=$!
dvtm -s "$FIFO" "$@" 2> /dev/null
kill $STATUS_PID
wait $STATUS_PID 2> /dev/null
rm -f "$FIFO"
